function money(x){return x||''}
function esc(x){return String(x||'')}
function priceNumber(p){return Number(String(p.price||'').replace(/[^0-9]/g,''))||0}
function rentMidpoint(p){const nums=String(p.rent||'').match(/\d+/g)||[];if(nums.length>=2)return Math.round((Number(nums[0])+Number(nums[1]))/2);if(nums.length===1)return Number(nums[0]);return 0}
function propertySearchText(p){return [p.address,p.suburb,p.region,p.type,p.land,p.floor,p.rent,p.cv,p.nearbySales,(p.features||[]).join(' '),(p.schoolZones||[]).join(' ')].join(' ').toLowerCase()}
function card(p){
  const cover=(p.images&&p.images[0])||p.image;
  return `<article class="card"><div class="image-wrap"><img class="listing-img" src="${cover}" alt="${p.address}">${p.imageNote?`<div class="image-note">${p.imageNote}</div>`:''}</div><div class="card-pad"><span class="pill">${p.badge}</span><div class="price">${p.price}</div><div class="meta"><b>${p.address}</b></div><div class="facts"><span class="fact">${p.beds} bed</span><span class="fact">${p.baths} bath</span><span class="fact">${p.parking} car</span></div><div class="compact-meta"><span>${p.suburb||''}</span><span>${p.region||''}</span><span>${p.floor||''} floor</span><span>Rent ${p.rent||'on request'}</span><span>CV ${p.cv||'on request'}</span></div><a class="btn alt" href="./listing.html?id=${p.id}">View property</a></div></article>`
}
function renderFeatured(limit=3){const el=document.querySelector('[data-featured]');if(!el)return;el.innerHTML=window.REALLIST_LISTINGS.slice(0,limit).map(card).join('')}
function getFilters(){return {q:(document.querySelector('[data-filter="q"]')?.value||'').trim().toLowerCase(),region:(document.querySelector('[data-filter="region"]')?.value||'').trim(),zone:(document.querySelector('[data-filter="zone"]')?.value||'').trim().toLowerCase(),min:Number(document.querySelector('[data-filter="min"]')?.value||0),max:Number(document.querySelector('[data-filter="max"]')?.value||0),beds:Number(document.querySelector('[data-filter="beds"]')?.value||0)}}
function filteredListings(){const f=getFilters();return window.REALLIST_LISTINGS.filter(p=>{const price=priceNumber(p);const hay=propertySearchText(p);const zones=(p.schoolZones||[]).join(' ').toLowerCase();if(f.q && !hay.includes(f.q))return false;if(f.region && p.region!==f.region)return false;if(f.zone && !zones.includes(f.zone))return false;if(f.min && price<f.min)return false;if(f.max && price>f.max)return false;if(f.beds && Number(p.beds)<f.beds)return false;return true})}
function renderListings(){const el=document.querySelector('[data-listings]');if(!el)return;const list=filteredListings();el.innerHTML=list.length?list.map(card).join(''):`<div class="empty-state">No matching properties yet. Try widening the filters or request free buyer guidance.</div>`;const result=document.querySelector('[data-filter-result]');if(result)result.textContent=`${list.length} matching ${list.length===1?'property':'properties'}.`}
function bindFilters(){if(!document.querySelector('[data-filter-bar]'))return;document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('input',renderListings));document.querySelector('[data-filter-reset]')?.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(el=>el.value='');renderListings()});const params=new URLSearchParams(location.search);const region=params.get('region');if(region){const r=document.querySelector('[data-filter="region"]'); if(r){r.value=region;}}}
function developmentToolkit(p){
 const addr=esc(p.address);
 const links=[
  ['Auckland Council GeoMaps','https://geomapspublic.aucklandcouncil.govt.nz/viewer/index.html','Check zoning, overlays, hazards, contours, boundaries and council map layers.'],
  ['Auckland Unitary Plan Viewer','https://unitaryplanmaps.aucklandcouncil.govt.nz/upviewer/','Check zoning, overlays, precincts and planning controls.'],
  ['Watercare GIS Viewer','https://www.watercare.co.nz/builders-and-developers/tools-fees-and-resources/gis-maps','Check water and wastewater networks, pipe locations and manholes.'],
  ['Watercare Network Capacity','https://www.watercare.co.nz/builders-and-developers/consultation/network-capacity-in-auckland','Check whether water and wastewater capacity may affect future development.'],
  ['Education Counts School Zones','https://www.educationcounts.govt.nz/find-school','Verify school enrolment zones directly.'],
  ['Council Rates & Valuation','https://www.aucklandcouncil.govt.nz/property-rates-valuations/Pages/find-property-rates-valuation.aspx','Check rating valuation and council property record information.']
 ];
 return `<div class="panel dev-toolkit"><div class="eyebrow">Property research links</div><h2>Council, services and school-zone checks</h2><p>${p.developmentNote||'Open the key public tools for this address. Useful for buyers, investors and developers who want to check zoning, services, school zones, rates and property information before going further.'}</p><div class="copy-row"><input class="input" value="${addr}" readonly><button class="btn alt" type="button" onclick="navigator.clipboard&&navigator.clipboard.writeText('${addr.replace(/'/g,"\\'")}')">Copy address</button></div><div class="tool-grid small-cards">${links.map(l=>`<a class="tool-card link-card" href="${l[1]}" target="_blank" rel="noopener"><h3>${l[0]}</h3><p>${l[2]}</p></a>`).join('')}</div><h3>Quick checks</h3><ul class="list"><li>Zone, overlays, precincts and planning controls</li><li>Water, wastewater and stormwater access</li><li>Flood plains, flood prone areas and overland flow paths</li><li>School enrolment zones and council rating information</li><li>Road frontage, access, slope and obvious site constraints</li><li>For development buyers: infrastructure capacity and professional feasibility</li></ul><p class="muted small">These links are provided for general guidance only. Reallist does not guarantee zoning, service capacity, school-zone eligibility, subdivision, development feasibility, council approval or planning outcomes. Buyers should seek independent advice from a planner, surveyor, architect, civil engineer, solicitor and other relevant professionals where needed.</p></div>`
}
function decisionSupport(p){
 return `<div class="panel"><div class="eyebrow">Decision support</div><h2>Before you go further</h2><div class="tool-grid small-cards"><div class="tool-card"><h3>For home buyers</h3><p>Check price reality, documents, condition, location fit, insurance and offer readiness before making a decision.</p></div><div class="tool-card"><h3>For investors</h3><p>Check rent, gross yield, repayment pressure, rates, insurance, maintenance, management fees and vacancy risk.</p></div><div class="tool-card"><h3>Before you offer</h3><p>Request documents, nearby sales and private viewing. Confirm finance, solicitor review, insurance and conditions.</p></div></div></div>`
}
function calculatorBlock(p){
 const price=priceNumber(p)||800000, rent=rentMidpoint(p)||750, dep=Math.round(price*0.2);
 return `<div class="panel" id="calculator"><div class="eyebrow">Mortgage & cashflow calculator</div><h2>Test the numbers</h2><div class="calc" data-calculator><div class="calc-grid"><label>Purchase price<input class="input" data-calc="price" type="number" value="${price}"></label><label>Deposit<input class="input" data-calc="deposit" type="number" value="${dep}"></label><label>Interest rate %<input class="input" data-calc="rate" type="number" step="0.01" value="6.85"></label><label>Loan term years<input class="input" data-calc="term" type="number" value="30"></label><label>Weekly rent<input class="input" data-calc="rent" type="number" value="${rent}"></label><label>Weekly expenses estimate<input class="input" data-calc="expenses" type="number" value="180"></label></div><div class="calc-results"><div><span>Loan amount</span><b data-result="loan">-</b></div><div><span>Weekly repayment</span><b data-result="weekly">-</b></div><div><span>Monthly repayment</span><b data-result="monthly">-</b></div><div><span>Rough weekly cashflow before tax</span><b data-result="cashflow">-</b></div></div><p class="muted small">This tool is for general information only and is not financial, legal, tax, lending or investment advice. Seek independent advice before making an offer.</p></div></div>`
}
function renderListing(){
  const holder=document.querySelector('[data-listing-detail]');if(!holder)return;
  const id=new URLSearchParams(location.search).get('id')||'rl-001';
  const p=window.REALLIST_LISTINGS.find(x=>x.id===id)||window.REALLIST_LISTINGS[0];
  document.title=`${p.address} | Reallist`;
  const imgs=(p.images&&p.images.length?p.images:[p.image]);
  const gallery=`<div class="gallery"><div class="image-wrap hero-image"><img src="${imgs[0]}" alt="${p.address}">${p.imageNote?`<div class="image-note">${p.imageNote}</div>`:''}</div>${imgs.length>1?`<div class="thumb-grid">${imgs.slice(1,13).map((img,i)=>`<img src="${img}" alt="${p.address} photo ${i+2}">`).join('')}</div>`:`<p class="muted" style="margin:12px 0 0">More photos can be added once the full approved image set is provided.</p>`}</div>`;
  const floorPlan = p.floorPlan ? `<div class="panel"><h2>Floor plan</h2><img class="floor-plan" src="${p.floorPlan}" alt="${p.address} floor plan"><p class="muted">Floor plan supplied from the approved listing material. Buyers should confirm exact dimensions before making an offer.</p></div>` : '';
  document.querySelector('[data-listing-hero]').innerHTML=`${gallery}<div class="panel"><span class="pill">${p.status}</span><h1 class="h1" style="font-size:52px">${p.price}</h1><h2>${p.address}</h2><p class="lead">${p.summary}</p><div class="facts"><span class="fact">${p.beds} bed</span><span class="fact">${p.baths} bath</span><span class="fact">${p.parking} car</span><span class="fact">${p.type}</span></div><a class="btn" href="#enquiry">Get free consulting</a></div>`;
  holder.innerHTML=`<div class="panel"><h2>Property snapshot</h2><table class="table"><tr><td>Property type</td><td><b>${p.type}</b></td></tr><tr><td>Auckland area</td><td><b>${p.region||''}</b></td></tr><tr><td>Land/title</td><td><b>${p.land}</b></td></tr><tr><td>Floor area</td><td><b>${p.floor}</b></td></tr><tr><td>Estimated rent</td><td><b>${p.rent}</b></td></tr><tr><td>Gross yield</td><td><b>${p.yield}</b></td></tr><tr><td>Viewing</td><td><b>${p.viewing||'Private viewing by request'}</b></td></tr></table></div><div class="panel"><h2>Description</h2><p>${p.summary}</p><h3>Key features</h3><ul class="list">${(p.features||[]).map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Price transparency</h2><p><b>Current asking price:</b> ${p.price}</p><p><b>Original price:</b> ${p.originalPrice}</p><p><b>Council CV:</b> ${p.cv}</p><p class="muted">Council CV is rating valuation information and should not be treated as current market valuation.</p><p><b>Nearby sales:</b> ${p.nearbySales}</p><ul class="list">${p.priceHistory.map(x=>`<li>${x}</li>`).join('')}</ul></div>${decisionSupport(p)}${calculatorBlock(p)}${developmentToolkit(p)}<div class="panel"><h2>School zones</h2><ul class="list">${(p.schoolZones||[]).map(x=>`<li>${x}</li>`).join('')}</ul><p class="muted">School zone information should be independently checked with the school or official zoning sources before purchase.</p></div>${floorPlan}<div class="panel"><h2>Who this may suit</h2><ul class="list">${p.suitableFor.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Watch before you offer</h2><ul class="list">${p.watchouts.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Document centre</h2><ul class="list">${p.documents.map(x=>`<li>${x}</li>`).join('')}</ul><p class="muted">Documents are supplied by the vendor/agency where available. Buyers should obtain independent legal and technical advice.</p></div>`;
  const prop=document.querySelector('[name="property"]'); if(prop) prop.value=p.address;
  initCalculators();
}
function initCalculators(){document.querySelectorAll('[data-calculator]').forEach(calc=>{function val(k){return Number(calc.querySelector(`[data-calc="${k}"]`)?.value||0)}function set(k,v){const el=calc.querySelector(`[data-result="${k}"]`);if(el)el.textContent=v}function fmt(n){return '$'+Math.round(n).toLocaleString()}function run(){const price=val('price'),deposit=val('deposit'),loan=Math.max(price-deposit,0),rate=val('rate')/100/12,term=val('term')*12,rent=val('rent'),expenses=val('expenses');let monthly=0;if(loan&&rate&&term){monthly=loan*rate*Math.pow(1+rate,term)/(Math.pow(1+rate,term)-1)}const weekly=monthly*12/52;const cash=rent-weekly-expenses;set('loan',fmt(loan));set('weekly',fmt(weekly));set('monthly',fmt(monthly));set('cashflow',(cash<0?'-':'')+fmt(Math.abs(cash))) }calc.querySelectorAll('input').forEach(i=>i.addEventListener('input',run));run();})}
renderFeatured();bindFilters();renderListings();renderListing();initCalculators();
