function money(x){return x||''}
function esc(x){return String(x||'')}
function priceNumber(p){return Number(String(p.price||'').replace(/[^0-9]/g,''))||0}
function propertySearchText(p){return [p.address,p.suburb,p.region,p.type,p.land,p.floor,p.rent,p.cv,p.nearbySales,(p.features||[]).join(' '),(p.schoolZones||[]).join(' ')].join(' ').toLowerCase()}
function card(p){
  const cover=(p.images&&p.images[0])||p.image;
  return `<article class="card"><div class="image-wrap"><img class="listing-img" src="${cover}" alt="${p.address}">${p.imageNote?`<div class="image-note">${p.imageNote}</div>`:''}</div><div class="card-pad"><span class="pill">${p.badge}</span><div class="price">${p.price}</div><div class="meta">${p.address}</div><div class="facts"><span class="fact">${p.beds} bed</span><span class="fact">${p.baths} bath</span><span class="fact">${p.parking} car</span></div><div class="compact-meta"><span>${p.suburb||''}</span><span>${p.region||''}</span><span>${p.floor||''} floor</span><span>Rent ${p.rent||'on request'}</span></div><a class="btn alt" href="./listing.html?id=${p.id}">View property</a></div></article>`
}
function renderFeatured(limit=3){const el=document.querySelector('[data-featured]');if(!el)return;el.innerHTML=window.REALLIST_LISTINGS.slice(0,limit).map(card).join('')}
function getFilters(){return {q:(document.querySelector('[data-filter="q"]')?.value||'').trim().toLowerCase(),region:(document.querySelector('[data-filter="region"]')?.value||'').trim(),zone:(document.querySelector('[data-filter="zone"]')?.value||'').trim().toLowerCase(),min:Number(document.querySelector('[data-filter="min"]')?.value||0),max:Number(document.querySelector('[data-filter="max"]')?.value||0),beds:Number(document.querySelector('[data-filter="beds"]')?.value||0)}}
function filteredListings(){const f=getFilters();return window.REALLIST_LISTINGS.filter(p=>{const price=priceNumber(p);const hay=propertySearchText(p);const zones=(p.schoolZones||[]).join(' ').toLowerCase();if(f.q && !hay.includes(f.q))return false;if(f.region && p.region!==f.region)return false;if(f.zone && !zones.includes(f.zone))return false;if(f.min && price<f.min)return false;if(f.max && price>f.max)return false;if(f.beds && Number(p.beds)<f.beds)return false;return true})}
function renderListings(){const el=document.querySelector('[data-listings]');if(!el)return;const list=filteredListings();el.innerHTML=list.length?list.map(card).join(''):`<div class="empty-state">No matching properties yet. Try widening the filters or request buyer guidance.</div>`;const result=document.querySelector('[data-filter-result]');if(result)result.textContent=`${list.length} matching ${list.length===1?'property':'properties'}.`}
function bindFilters(){if(!document.querySelector('[data-filter-bar]'))return;document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('input',renderListings));document.querySelector('[data-filter-reset]')?.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(el=>el.value='');renderListings()})}
function renderListing(){
  const holder=document.querySelector('[data-listing-detail]');if(!holder)return;
  const id=new URLSearchParams(location.search).get('id')||'rl-001';
  const p=window.REALLIST_LISTINGS.find(x=>x.id===id)||window.REALLIST_LISTINGS[0];
  document.title=`${p.address} | Reallist`;
  const imgs=(p.images&&p.images.length?p.images:[p.image]);
  const gallery=`<div class="gallery"><div class="image-wrap hero-image"><img src="${imgs[0]}" alt="${p.address}">${p.imageNote?`<div class="image-note">${p.imageNote}</div>`:''}</div>${imgs.length>1?`<div class="thumb-grid">${imgs.slice(1,13).map((img,i)=>`<img src="${img}" alt="${p.address} photo ${i+2}">`).join('')}</div>`:`<p class="muted" style="margin:12px 0 0">More photos can be added once the full approved image set is provided.</p>`}</div>`;
  const floorPlan = p.floorPlan ? `<div class="panel"><h2>Floor plan</h2><img class="floor-plan" src="${p.floorPlan}" alt="${p.address} floor plan"><p class="muted">Floor plan supplied from the approved listing material. Buyers should confirm exact dimensions before making an offer.</p></div>` : '';
  document.querySelector('[data-listing-hero]').innerHTML=`${gallery}<div class="panel"><span class="pill">${p.status}</span><h1 class="h1" style="font-size:52px">${p.price}</h1><h2>${p.address}</h2><p class="lead">${p.summary}</p><div class="facts"><span class="fact">${p.beds} bed</span><span class="fact">${p.baths} bath</span><span class="fact">${p.parking} car</span><span class="fact">${p.type}</span></div><a class="btn" href="#enquiry">Request documents / nearby sales / viewing</a></div>`;
  holder.innerHTML=`<div class="panel"><h2>Property snapshot</h2><table class="table"><tr><td>Property type</td><td><b>${p.type}</b></td></tr><tr><td>Auckland area</td><td><b>${p.region||''}</b></td></tr><tr><td>Land/title</td><td><b>${p.land}</b></td></tr><tr><td>Floor area</td><td><b>${p.floor}</b></td></tr><tr><td>Estimated rent</td><td><b>${p.rent}</b></td></tr><tr><td>Gross yield</td><td><b>${p.yield}</b></td></tr><tr><td>Viewing</td><td><b>${p.viewing||'Private viewing by request'}</b></td></tr></table></div><div class="panel"><h2>Description</h2><p>${p.summary}</p><h3>Key features</h3><ul class="list">${(p.features||[]).map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Price transparency</h2><p><b>Current asking price:</b> ${p.price}</p><p><b>Original price:</b> ${p.originalPrice}</p><p><b>Council CV:</b> ${p.cv}</p><p class="muted">Council CV is rating valuation information and should not be treated as current market valuation.</p><p><b>Nearby sales:</b> ${p.nearbySales}</p><ul class="list">${p.priceHistory.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>School zones</h2><ul class="list">${(p.schoolZones||[]).map(x=>`<li>${x}</li>`).join('')}</ul><p class="muted">School zone information should be independently checked with the school or official zoning sources before purchase.</p></div>${floorPlan}<div class="panel"><h2>Who this may suit</h2><ul class="list">${p.suitableFor.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Watch before you offer</h2><ul class="list">${p.watchouts.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel"><h2>Document centre</h2><ul class="list">${p.documents.map(x=>`<li>${x}</li>`).join('')}</ul><p class="muted">Documents are supplied by the vendor/agency where available. Buyers should obtain independent legal and technical advice.</p></div>`;
  const prop=document.querySelector('[name="property"]'); if(prop) prop.value=p.address;
}
renderFeatured();bindFilters();renderListings();renderListing();
